#define STANDARD_WAVE "standard wave"
#define SUICIDE_WAVE "suicide wave"
#define AIR_ASSAULT_WAVE "air assault wave"
#define CIVILIAN_WAVE "civlian wave"
#define DRONE_WAVE "drone wave"
#define MORTAR_WAVE "mortar wave"
#define DEFECTOR_WAVE "defector wave"
#define OVERRUN_WAVE "overrun wave"