#define INFO_PANEL_DISPLAYNAME "BLWK_infoPanel"
#define INFO_PANEL_IDD 9291
#define INFO_PANEL_PLAYER_POINTS_IDC 1001
#define INFO_PANEL_WAVE_NUM_IDC 1003
#define INFO_PANEL_RESPAWNS_NUM_IDC 1004
#define INFO_PANEL_WAVE_STATUS_IDC 1007