#define BLWK_MUSIC_MANAGER_IDD 61500

#define BLWK_MUSIC_MANAGER_CURRENT_PLAYLIST_IDC 61501
#define BLWK_MUSIC_MANAGER_SONGS_LIST_IDC 61502

#define BLWK_MUSIC_MANAGER_CLOSE_BUTTON_IDC 61504

#define BLWK_MUSIC_MANAGER_COMMIT_BUTTON_IDC 61505

#define BLWK_MUSIC_MANAGER_TIMELINE_SLIDER_IDC 61506
#define BLWK_MUSIC_MANAGER_VOLUME_SLIDER_IDC 61507

#define BLWK_MUSIC_MANAGER_PLAY_BUTTON_IDC 61508
#define BLWK_MUSIC_MANAGER_PAUSE_BUTTON_IDC 61509

#define BLWK_MUSIC_MANAGER_SPACING_EDIT_IDC 61510
#define BLWK_MUSIC_MANAGER_SPACING_BUTTON_IDC 61511
#define BLWK_MUSIC_MANAGER_SPACING_COMBO_IDC 61512

#define BLWK_MUSIC_MANAGER_ONOFF_COMBO_IDC 61513

#define BLWK_MUSIC_MANAGER_SAVEAS_BUTTON_IDC 61503
#define BLWK_MUSIC_MANAGER_SAVE_EDIT_IDC 61514
#define BLWK_MUSIC_MANAGER_SAVE_BUTTON_IDC 61515

#define BLWK_MUSIC_MANAGER_LOAD_COMBO_IDC 61516
#define BLWK_MUSIC_MANAGER_LOAD_PLAYLIST_BUTTON_IDC 61517

#define BLWK_MUSIC_MANAGER_ADDTO_BUTTON_IDC 61518
#define BLWK_MUSIC_MANAGER_REMOVEFROM_BUTTON_IDC 61519

#define BLWK_MUSIC_MANAGER_DELETE_BUTTON_IDC 61520


#define BLWK_PUB_CURRENT_PLAYLIST KISKA_musicManager_currentPlaylist

#ifndef TO_STRING
#define TO_STRING(NAME) #NAME
#endif

#define GET_PUBLIC_ARRAY_DEFAULT (missionNamespace getVariable [TO_STRING(BLWK_PUB_CURRENT_PLAYLIST),[]])

#ifndef CT_EDIT
#define CT_EDIT 2
#endif

#ifndef CT_XSLIDER
#define CT_XSLIDER 43
#endif

#ifndef CT_SLIDER
#define CT_SLIDER 3
#endif