#define BLWK_SHOP_IDD 97900

#define BLWK_SHOP_CLOSE_BUTT_IDC 97920 // highest

#define BLWK_SHOP_BUILD_PURCHASE_SELF_BUTT_IDC 97901
#define BLWK_SHOP_BUILD_PURCHASE_POOL_BUTT_IDC 97902

#define BLWK_SHOP_SUPP_PURCHASE_SELF_BUTT_IDC 97903
#define BLWK_SHOP_SUPP_PURCHASE_POOL_BUTT_IDC 97904

#define BLWK_SHOP_POOL_WITHDRAW_BUTT_IDC 97905
#define BLWK_SHOP_POOL_SELL_BUTT_IDC 97919

#define BLWK_SHOP_POINTS_DEPOSIT_BUTT_IDC 97906
#define BLWK_SHOP_POINTS_WITHDRAW_BUTT_IDC 97907

#define BLWK_SHOP_SUPP_EDIT_IDC 97908
#define BLWK_SHOP_BUILD_EDIT_IDC 97909
#define BLWK_SHOP_POOL_EDIT_IDC 97910

#define BLWK_SHOP_POINTS_WITHDRAW_EDIT_IDC 97911
#define BLWK_SHOP_POINTS_DEPOSIT_EDIT_IDC 97912
#define BLWK_SHOP_POINTS_WITHDRAW_SLIDER_IDC 97913
#define BLWK_SHOP_POINTS_DEPOSIT_SLIDER_IDC 97914

#define BLWK_SHOP_SUPP_TREE_IDC 97915
#define BLWK_SHOP_BUILD_TREE_IDC 97916
#define BLWK_SHOP_POOL_TREE_IDC 97917

#define BLWK_SHOP_PREVIEW_IDC 97918

#define BLWK_SHOP_BUILD_POOL_GVAR BLWK_objectPoolInfo
#define BLWK_SHOP_SUPP_POOL_GVAR BLWK_supportPoolInfo

#ifndef TO_STRING
#define TO_STRING(NAME) #NAME
#endif

#ifndef CT_EDIT
#define CT_EDIT 2
#endif

#ifndef CT_XSLIDER
#define CT_XSLIDER 43
#endif

#ifndef CT_SLIDER
#define CT_SLIDER 3
#endif


#define SHOP_DIALOG_STRING "theCrateShopDialog"

// other can be either in both support and build items
#define OTHER_CATEGORY "Other"

// categories for build items
#define WALLS_CATEGORY "Walls"
#define PLATFORMS_CATEGORY "Platforms"
#define SANDBAGS_CATEGORY "Sandbags"
#define OBSTACLES_CATEGORY "Obstacles"
#define LAMPS_CATEGORY "Lamps"
#define TOWERS_CATEGORY "Towers"
#define BUNKERS_CATEGORY "Bunkers"
#define VERTICAL_CATEGORY "Ramps & Stairs"
#define TURRETS_CATEGORY "Turrets"
#define STORAGE_CATEGORY "Storage"
#define BUILDINGS_CATEGORY "Buildings"
#define HBARR_CATEGORY "H-Barriers"
#define UNIQUE_CATEGORY "Unique Items"
#define TRENCH_CATEGORY "Trenches"
#define REVETMENT_CATEGORY "Revetments"

// categories for support items
#define HEAVY_ARTILLERY_CATEGORY "Heavy Artillery"
#define CANNON_CATEGORY "Ship Cannon"
#define LIGHT_MORTAR_CATEGORY "Light Mortars"
#define CAS_CATEGORY "Close Air Support"
#define GUNNER_CATEGORY "Aircraft Gunner"
#define SUPPLY_CATEGORY "Supplies"
#define REINFORCEMENTS_CATEGORY "Reinforcements"
#define RECON_CATEGORY "Recon"
