#define GUN_RUN_ID 0
#define GUNS_AND_ROCKETS_ARMOR_PIERCING_ID 1
#define GUNS_AND_ROCKETS_HE_ID 2
#define ROCKETS_ARMOR_PIERCING_ID 3
#define ROCKETS_HE_ID 4
#define AGM_ID 5
#define BOMB_LGB_ID 6
#define BOMB_CLUSTER_ID 7
#define BOMB_NAPALM_ID 8

#define CANNON_TYPE "CANNON"
#define AGM_TYPE "AGM"
#define ROCKETS_AP_TYPE "ROCKETS_AP"
#define ROCKETS_HE_TYPE "ROCKETS_HE"
#define BOMB_LGB_TYPE "BOMB_LGB"
#define BOMB_UGB_TYPE "BOMB_UGB"
