_classes1 = [
	"HFMP_Abstract",
	"HFMP_FinishTheFight",
	"HFMP_Greenhorns",
	"HFMP_NeoMombasa",
	"HFMP_Songheili",
	"HFMP_sketchBook1_2",
	"HFMP_sketchBook1_3",
	"HFMP_sketchBook1_4",
	"HFMP_sketchBook1_5",
	"HFMP_sketchBook1_6",
	"HFMP_sketchBook1_7",
	"HFMP_sketchBook1_8",
	"HFMP_sketchBook1_9",
	"HFMP_sketchBook2_1",
	"HFMP_sketchBook2_2",
	"HFMP_sketchBook2_3",
	"HFMP_sketchBook2_4",
	"HFMP_sketchBook2_5",
	"HFMP_sketchBook2_6",
	"HFMP_sketchBook2_7",
	"HFMP_sketchBook2_8",
	"HFMP_sketchBook2_9",
	"HFMP_sketchBook2_10",
	"HFMP_sketchBook2_11",
	"HFMP_sketchBook2_12",
	"HFMP_sketchBook2_13",
	"HFMP_sketchBook2_14",
	"HFMP_sketchBook2_15",
	"HFMP_sketchBook2_16",
	"HFMP_sketchBook2_17",
	"HFMP_sketchBook2_18",
	"HFMP_sketchBook2_19",
	"HFMP_sketchBook2_20",
	"HFMP_sketchBook2_21",
	"HFMP_sketchBook2_22",
	"HFMP_TruthReconciliation",
	"HFMP_SlipspaceTrajectory",
	"HFMP_BellyOfTheBeast",
	"HFMP_BrothersInArms",
	"HFMP_NotANaturalFormation",
	"HFMP_EnoughDeadHeroes",
	"HFMP_AWalkInTheWoods",
	"HFMP_InAmberClad",
	"HFMP_PerilousJourney",
	"HFMP_UnderCoverOfNight",
	"HFMP_PompAndCircumstance",
	"HFMP_LamentForPvtJenkins",
	"HFMP_AmbientWonder",
	"HFMP_AlienCorridors",
	"HFMP_RockAnthemForSavingTheWorld",
	"HFMP_PercussionAnthemForSavingTheWorld",
	"HFMP_TheGunPointedAtTheHeadOfTheUniverse",
	"HFMP_TheLongRun",
	"HFMP_OnAPaleHorse",
	"HFMP_CovenantDance",
	"HFMP_RockAnthemEvolved",
	"HFMP_TheSiegeOfMadrigal",
	"HFMP_KeepWhatYouSteal",
	"HFMP_DevilsMonsters",
	"HFMP_Unyielding",
	"HFMP_Leonidas",
	"HFMP_Drumrun",
	"HFMP_SuiteAutumn1",
	"HFMP_SuiteAutumn2",
	"HFMP_TheMaw",
	"HFMP_WarthogRun",
	"HFMP_DustAndEchoes",
	"HFMP_Halo",
	"HFMP_PerchanceToADream",
	"HFMP_TheLostMuse",
	"HFMP_SleepingGrunts"	
];


_classes = ["TOG_musicClass"] call KISKA_fnc_getMusicFromClass;

_classes1 append _classes;

null = [false,"",_classes1,1] spawn KISKA_fnc_randomMusic;