// MSV
#define RHS_AFRF_RUS_MSV_EMR_UNITS \
[\
	"rhs_msv_emr_at",\
	"rhs_msv_emr_arifleman",\
	"rhs_msv_emr_engineer",\
	"rhs_msv_emr_grenadier_rpg",\
	"rhs_msv_emr_strelok_rpg_assist",\
	"rhs_msv_emr_junior_sergeant",\
	"rhs_msv_emr_machinegunner",\
	"rhs_msv_emr_machinegunner_assistant",\
	"rhs_msv_emr_marksman",\
	"rhs_msv_emr_medic",\
	"rhs_msv_emr_rifleman",\
	"rhs_msv_emr_grenadier",\
	"rhs_msv_emr_LAT",\
	"rhs_msv_emr_RShG2",\
	"rhs_msv_emr_sergeant",\
	["rhs_tigr_sts_msv","rhs_btr70_msv","rhs_bmp3_msv","rhs_t80um","rhs_ka60_c","RHS_Mi8mt_vvsc","RHS_Su25SM_vvsc"]\
]
#define RHS_AFRF_RUS_MSV_FLORA_UNITS \
[\
	"rhs_msv_at",\
	"rhs_msv_arifleman",\
	"rhs_msv_engineer",\
	"rhs_msv_grenadier_rpg",\
	"rhs_msv_strelok_rpg_assist",\
	"rhs_msv_junior_sergeant",\
	"rhs_msv_machinegunner",\
	"rhs_msv_machinegunner_assistant",\
	"rhs_msv_marksman",\
	"rhs_msv_medic",\
	"rhs_msv_rifleman",\
	"rhs_msv_grenadier",\
	"rhs_msv_LAT",\
	"rhs_msv_RShG2",\
	"rhs_msv_sergeant",\
	["rhs_tigr_sts_msv","rhs_btr70_msv","rhs_bmp3_msv","rhs_t80um","rhs_ka60_c","RHS_Mi8mt_vvsc","RHS_Su25SM_vvsc"]\
]


// VDV
#define RHS_AFRF_RUS_VDV_EMR_UNITS \
[\
	"rhs_vdv_at",\
	"rhs_vdv_arifleman",\
	"rhs_vdv_engineer",\
	"rhs_vdv_grenadier_rpg",\
	"rhs_vdv_strelok_rpg_assist",\
	"rhs_vdv_junior_sergeant",\
	"rhs_vdv_machinegunner",\
	"rhs_vdv_machinegunner_assistant",\
	"rhs_vdv_marksman",\
	"rhs_vdv_marksman_asval",\
	"rhs_vdv_medic",\
	"rhs_vdv_rifleman",\
	"rhs_vdv_rifleman_asval",\
	"rhs_vdv_grenadier",\
	"rhs_vdv_grenadier_alt",\
	"rhs_vdv_LAT",\
	"rhs_vdv_RShG2",\
	"rhs_vdv_rifleman_alt",\
	"rhs_vdv_sergeant",\
	["rhs_tigr_sts_vdv","rhs_btr80a_vdv","rhs_bmd4_vdv","rhs_sprut_vdv","rhs_ka60_c","RHS_Mi8mt_vdv","RHS_Su25SM_vvsc"]\
]
#define RHS_AFRF_RUS_VDV_EMR_DES_UNITS \
[\
	"rhs_vdv_des_at",\
	"rhs_vdv_des_arifleman",\
	"rhs_vdv_des_engineer",\
	"rhs_vdv_des_grenadier_rpg",\
	"rhs_vdv_des_strelok_rpg_assist",\
	"rhs_vdv_des_junior_sergeant",\
	"rhs_vdv_des_machinegunner",\
	"rhs_vdv_des_machinegunner_assistant",\
	"rhs_vdv_des_marksman",\
	"rhs_vdv_des_marksman_asval",\
	"rhs_vdv_des_medic",\
	"rhs_vdv_des_rifleman",\
	"rhs_vdv_des_rifleman_asval",\
	"rhs_vdv_des_grenadier",\
	"rhs_vdv_des_LAT",\
	"rhs_vdv_des_RShG2",\
	"rhs_vdv_des_sergeant",\
	["rhs_tigr_sts_3camo_vdv","rhs_btr80a_vdv","rhs_bmd4_vdv","rhs_sprut_vdv","rhs_ka60_c","RHS_Mi8mt_vdv","RHS_Su25SM_vvsc"]\
]
#define RHS_AFRF_RUS_VDV_FLORA_UNITS \
[\
	"rhs_vdv_flora_at",\
	"rhs_vdv_flora_engineer",\
	"rhs_vdv_flora_grenadier_rpg",\
	"rhs_vdv_flora_strelok_rpg_assist",\
	"rhs_vdv_flora_junior_sergeant",\
	"rhs_vdv_flora_machinegunner",\
	"rhs_vdv_flora_machinegunner_assistant",\
	"rhs_vdv_flora_marksman",\
	"rhs_vdv_flora_medic",\
	"rhs_vdv_flora_rifleman",\
	"rhs_vdv_flora_grenadier",\
	"rhs_vdv_flora_LAT",\
	"rhs_vdv_flora_RShG2",\
	"rhs_vdv_flora_sergeant",\
	["rhs_tigr_sts_vdv","rhs_btr80a_vdv","rhs_bmd4_vdv","rhs_sprut_vdv","rhs_ka60_c","RHS_Mi8mt_vdv","RHS_Su25SM_vvsc"]\
]
#define RHS_AFRF_RUS_VDV_MFLORA_UNITS \
[\
	"rhs_vdv_mflora_at",\
	"rhs_vdv_mflora_engineer",\
	"rhs_vdv_mflora_grenadier_rpg",\
	"rhs_vdv_mflora_strelok_rpg_assist",\
	"rhs_vdv_mflora_junior_sergeant",\
	"rhs_vdv_mflora_machinegunner",\
	"rhs_vdv_mflora_machinegunner_assistant",\
	"rhs_vdv_mflora_marksman",\
	"rhs_vdv_mflora_medic",\
	"rhs_vdv_mflora_rifleman",\
	"rhs_vdv_mflora_grenadier",\
	"rhs_vdv_mflora_LAT",\
	"rhs_vdv_mflora_RShG2",\
	"rhs_vdv_mflora_sergeant",\
	["rhs_tigr_sts_3camo_vdv","rhs_btr80a_vdv","rhs_bmd4_vdv","rhs_sprut_vdv","rhs_ka60_c","RHS_Mi8mt_vdv","RHS_Su25SM_vvsc"]\
]
#define RHS_AFRF_RUS_VDV_RECON_UNITS \
[\
	"rhs_vdv_recon_arifleman",\
	"rhs_vdv_recon_machinegunner_assistant",\
	"rhs_vdv_recon_marksman",\
	"rhs_vdv_recon_efreitor",\
	"rhs_vdv_recon_marksman_asval",\
	"rhs_vdv_recon_marksman_vss",\
	"rhs_vdv_recon_medic",\
	"rhs_vdv_recon_rifleman",\
	"rhs_vdv_recon_rifleman_ak103",\
	"rhs_vdv_recon_rifleman_akms",\
	"rhs_vdv_recon_rifleman_asval",\
	"rhs_vdv_recon_grenadier",\
	"rhs_vdv_recon_rifleman_lat",\
	"rhs_vdv_recon_rifleman_scout_akm",\
	"rhs_vdv_recon_rifleman_scout",\
	"rhs_vdv_recon_grenadier_scout",\
	"rhs_vdv_recon_arifleman_scout",\
	"rhs_vdv_recon_sergeant",\
	["rhs_tigr_sts_vdv","rhs_btr80a_vdv","rhs_bmd4_vdv","rhs_sprut_vdv","rhs_ka60_c","RHS_Mi8mt_vdv","RHS_Su25SM_vvsc"]\
]
#define RHS_AFRF_RUS_VMF_RECON_UNITS \
[\
	"rhs_vmf_recon_arifleman",\
	"rhs_vmf_recon_efreitor",\
	"rhs_vmf_recon_machinegunner_assistant",\
	"rhs_vmf_recon_marksman",\
	"rhs_vmf_recon_marksman_vss",\
	"rhs_vmf_recon_medic",\
	"rhs_vmf_recon_rifleman",\
	"rhs_vmf_recon_rifleman_akms",\
	"rhs_vmf_recon_rifleman_l",\
	"rhs_vmf_recon_rifleman_asval",\
	"rhs_vmf_recon_grenadier",\
	"rhs_vmf_recon_rifleman_lat",\
	"rhs_vmf_recon_rifleman_scout_akm",\
	"rhs_vmf_recon_rifleman_scout",\
	"rhs_vmf_recon_grenadier_scout",\
	"rhs_vmf_recon_arifleman_scout",\
	"rhs_vmf_recon_sergeant",\
	["rhs_tigr_sts_vdv","rhs_btr80a_vdv","rhs_bmd4_vdv","rhs_sprut_vdv","rhs_ka60_c","RHS_Mi8mt_vdv","RHS_Su25SM_vvsc"]\
]
#define RHS_AFRF_RUS_VMF_FLORA_UNITS \
[\
	"rhs_vmf_flora_at",\
	"rhs_vmf_flora_efreitor",\
	"rhs_vmf_flora_engineer",\
	"rhs_vmf_flora_grenadier_rpg",\
	"rhs_vmf_flora_strelok_rpg_assist",\
	"rhs_vmf_flora_junior_sergeant",\
	"rhs_vmf_flora_machinegunner",\
	"rhs_vmf_flora_machinegunner_assistant",\
	"rhs_vmf_flora_marksman",\
	"rhs_vmf_flora_medic",\
	"rhs_vmf_flora_rifleman",\
	"rhs_vmf_flora_grenadier",\
	"rhs_vmf_flora_LAT",\
	"rhs_vmf_flora_RShG2",\
	"rhs_vmf_flora_sergeant",\
	["rhs_tigr_sts_vdv","rhs_btr80a_vdv","rhs_bmd4_vdv","rhs_sprut_vdv","rhs_ka60_c","RHS_Mi8mt_vdv","RHS_Su25SM_vvsc"]\
]
#define RHS_AFRF_RUS_VV_OSN_UNITS \
[\
	"rhs_mvd_izlom_arifleman",\
	"rhs_mvd_izlom_efreitor",\
	"rhs_mvd_izlom_grenadier_rpg",\
	"rhs_mvd_izlom_machinegunner",\
	"rhs_mvd_izlom_marksman",\
	"rhs_mvd_izlom_marksman_vss",\
	"rhs_mvd_izlom_rifleman",\
	"rhs_mvd_izlom_rifleman_asval",\
	"rhs_mvd_izlom_rifleman_LAT",\
	"rhs_mvd_izlom_sergeant",\
	["rhs_tigr_sts_vdv","rhs_btr80a_vdv","rhs_bmd4_vdv","rhs_sprut_vdv","rhs_ka60_c","RHS_Mi8mt_vv","RHS_Su25SM_vvsc"]\
]