#define FACTION_STRINGS \
	"NATO", \
	"NATO PACIFIC", \
	"NATO WOODLAND", \
	"CTRG PACIFIC", \
	"CSAT", \
	"CSAT PACIFIC", \
	"CSAT URBAN", \
	"VIPER", \
	"VIPER PACIFIC", \
	"FIA", \
	"SYNDIKAT", \
	"AAF", \
	"LDF", \
	"SPETSNAZ (CONTACT)"

#define FACTION_VARS \
[ \
	NATO_UNITS, \
	NATO_PACIFIC_UNITS, \
	NATO_WOODLAND_UNITS, \
	CTRG_PACIFIC_UNITS, \
	CSAT_UNITS, \
	CSAT_PACIFIC_UNITS, \
	CSAT_URBAN_UNITS, \
	VIPER_UNITS, \
	VIPER_PACIFIC_UNITS, \
	FIA_UNITS, \
	SYNDIKAT_UNITS, \
	AAF_UNITS, \
	LDF_UNITS, \
	SPETZNAS_CONTACT_UNITS \
]