#define SPARTAN_GEAR \
    "OPTRE_MJOLNIR_Undersuit",\
    "OPTRE_FC_MJOLNIR_MKV_Armor",\
    "OPTRE_FC_MJOLNIR_MKV_Armor_Olive",\
    "OPTRE_FC_MJOLNIR_MKV_Armor_Black",\
    "OPTRE_FC_MJOLNIR_MKV_Armor_Night",\
    "OPTRE_FC_MJOLNIR_MKV_Armor_Freeman",\
    "OPTRE_FC_MJOLNIR_MKV_Armor_117",\
    "OPTRE_FC_MJOLNIR_MKVI_Undersuit",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_White",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_Olive",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_Tan",\
    "OPTRE_FC_MJOLNIR_MKV_Armor_Caboose",\
    "OPTRE_FC_MJOLNIR_MKV_Armor_Church",\
    "OPTRE_FC_MJOLNIR_MKV_Armor_Donut",\
    "OPTRE_FC_MJOLNIR_MKV_Armor_Grif",\
    "OPTRE_FC_MJOLNIR_MKV_Armor_Sarge",\
    "OPTRE_FC_MJOLNIR_MKV_Armor_Simmons",\
    "OPTRE_FC_MJOLNIR_MKV_Armor_Tucker","\
    OPTRE_FC_MJOLNIR_Mark_VI_Armor_Tex",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_Caboose",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_Church",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_Tucker","\
    OPTRE_FC_MJOLNIR_Mark_VI_Armor_Donut",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_Grif",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_Simmons",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_Sarge",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_Kaikaina",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_Lopez",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_Doc",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_North",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_South",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_York",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Armor_Washington",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_dp",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Olive",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Olive_dp",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Black",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Black_dp",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Night",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Night_dp",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Freeman",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Freeman_dp",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_117",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_117_dp",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_White",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Olive",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Tan",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Caboose",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Caboose_dp",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Church",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Church_dp",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Donut",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Donut_dp",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Grif",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Grif_dp",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Sarge",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Sarge_dp",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Simmons",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Simmons_dp",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Tucker",\
    "OPTRE_FC_MJOLNIR_MKV_Helmet_Tucker_dp",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Tex",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Caboose",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Church",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Donut",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Grif",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Simmons",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Sarge",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Kaikaina",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Lopez",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Doc",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_North",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_South",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_York",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Washington",\
    "OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Tucker",\
    "OPTRE_MJOLNIR_Dress_Uniform",\
    "OPTRE_MJOLNIR_Mk4Armor",\
    "OPTRE_MJOLNIR_Mk4Armor_Blue",\
    "OPTRE_MJOLNIR_Mk4Armor_Red",\
    "OPTRE_MJOLNIR_MkVBArmor",\
    "OPTRE_MJOLNIR_Mk4Helmet",\
    "OPTRE_MJOLNIR_Mk4Helmet_dp",\
    "OPTRE_MJOLNIR_Mk4Helmet_Blue",\
    "OPTRE_MJOLNIR_Mk4Helmet_Blue_dp",\
    "OPTRE_MJOLNIR_Mk4Helmet_Red",\
    "OPTRE_MJOLNIR_Mk4Helmet_Red_dp",\
    "OPTRE_MJOLNIR_MkVBHelmet",\
    "OPTRE_MJOLNIR_MkVBHelmet_dp",\
    "OPTRE_MJOLNIR_EVAHelmet",\
    "OPTRE_MJOLNIR_EVAHelmet_dp",\
    "OPTRE_MJOLNIR_EVAHelmet_Emily",\
    "OPTRE_MJOLNIR_EVAHelmet_Emily_dp",\
    "OPTRE_MJOLNIR_ReconHelmet",\
    "OPTRE_MJOLNIR_ReconHelmet_dp",\
    "OPTRE_MJOLNIR_MPHelmet",\
    "OPTRE_MJOLNIR_MPHelmet_dp",\
    "OPTRE_MJOLNIR_Dress_Hat",\
    "OPTRE_FC_Spartan_Uniform",\
    "OPTRE_UNSC_Rucksack_Spartan",\
    "OPTRE_UNSC_Rucksack_Heavy_M41G_Spartan",\
    "OPTRE_UNSC_Rucksack_Heavy_M73_Spartan",\
    "OPTRE_UNSC_Rucksack_Heavy_Spartan",\
    "OPTRE_UNSC_Rucksack_Lead_Spartan",\
    "OPTRE_UNSC_Rucksack_M41_Spartan",\
    "OPTRE_UNSC_Rucksack_Medic_Filled_Spartan",\
    "OPTRE_UNSC_Rucksack_Medic_Spartan",\
    "OPTRE_UNSC_Rucksack_Spartan",\
    "OPTRE_S12_SOLA_Jetpack_Spartan",\
    "OPTRE_S12_SOLA_Jetpack_On_Spartan",\
    "OPTRE_ILCS_Rucksack_Medical_Spartan",\
    "OPTRE_ILCS_Rucksack_Medical_Filled_Spartan",\
    "OPTRE_ILCS_Rucksack_Heavy_Spartan",\
    "OPTRE_ILCS_Rucksack_Heavy_M73_Spartan",\
    "OPTRE_ILCS_Rucksack_Heavy_M41G_Spartan",\
    "OPTRE_ILCS_Rucksack_Heavy_Demo_Spartan",\
    "OPTRE_ILCS_Rucksack_Black_Spartan",\
    "OPTRE_ILCS_Rucksack_Black_M41_Spartan",\
    "OPTRE_ILCS_Rucksack_Black_Lead_Spartan",\
    "OPTRE_Fury_Backpack_Nuke_Spartan"
